linters:
  rubocop:
    display_cop_names: true
files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"

- name: Pull Request Linter
  uses: MorrisonCole/pr-lint-action@v1.5.0
